### ISSUE TITLE
Build Error - undefined value

### ISSUE THREAD

**Issue by treyhardin** [treyhardin/Raspberry-Pi-Synth#1]
Getting an error on build:

```
TypeError: Cannot read property 'toLowerCase' of undefined
    at Array.some (<anonymous>)
```

Have tried clearing npm cache, and temporarily removing all lines including toLowerCase. Plz help

**Comment by jimmyhogerty** [comment]
on it. 

![Screen Shot 2022-07-18 at 8 22 13 AM](https://user-images.githubusercontent.com/43115008/179545467-ad317891-ba34-4394-9885-42c6dfbe00fc.png)
